[build-system]
requires = [
    "setuptools>=42",
    "wheel",
]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 88
target-version = ['py37', 'py38']
exclude = '''
( 
| \.egg
| \.git
| \.tox
| \.venv
| setup.py
| build
| dist
)
'''
